# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d36c73b472ed7674dc8315b3a2515f6e"
name = "gbi-curtain-pricing"
application_url = "https://gbi-curtain-pricing.icecubedev.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_cart_transforms,read_publications,write_publications"

[auth]
redirect_urls = [ "https://gbi-curtain-pricing.icecubedev.com/api/auth" ]

